#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged #--concurrent false

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^((feature|bugfix|hotfix)\/[a-z0-9-]+|release|master|test|staging)$"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi
